DROP TABLE IF EXISTS `Users`;
CREATE TABLE IF NOT EXISTS `Users` (
    `ID` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
    `PublicKey` CHAR(44) NOT NULL UNIQUE,
    `Username` VARCHAR(100) NOT NULL UNIQUE
);
DROP TABLE IF EXISTS `Posts`;
CREATE TABLE IF NOT EXISTS `Posts` (
    `ID` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
    `Content` TEXT NOT NULL,
    `Nonce` TEXT NOT NULL,
    `UserID` INTEGER NOT NULL,
    `TimePosted` TEXT NOT NULL,
    `PublicKey` TEXT NOT NULL,
    `PublicKeyNonce` TEXT NOT NULL
);
DROP TABLE IF EXISTS `NOA`;
CREATE TABLE IF NOT EXISTS `NOA` (
    `UserID` INTEGER NOT NULL,
    `PostID` INTEGER NOT NULL,
    `SecretKey` TEXT NOT NULL,
    `Nonce` TEXT NOT NULL,
    PRIMARY KEY(`PostID`,`UserID`)
);
DROP TABLE IF EXISTS `Auth`;
CREATE TABLE IF NOT EXISTS `Auth` (
    `PublicKey` CHAR(44) NOT NULL PRIMARY KEY UNIQUE,
    `ExpectedToken` TEXT NOT NULL,
    `Timeout` TEXT NOT NULL
);
