# This document specifies the style guidelines for this code, maintained by
# `rustfmt` / `cargo fmt`

indent_style = "Block"  # Indentation levels are fixed, rather than visual
use_small_heuristics = "Max"  # Encourage short onelines `if value { then }`
binop_separator = "Front"  # Place operators at the start of a new line
combine_control_expr = false  # Do not allow `function(if value ...`, break
comment_width = 80  # Comments may be up to 80 characters wide
condense_wildcard_suffixes = true  # convert `_, _` into `..`
control_brace_style = "AlwaysSameLine"  # Curly braces on same line as control
fn_args_density = "Tall"  # Function args fill until break, then all on new line
brace_style = "SameLineWhere"  # Braces on same line, except for where clauses
empty_item_single_line = true  # Allow empty items on a single line
enum_discrim_align_threshold = 0  # Do not align enum values
fn_single_line = true  # Put single-expression functions on a single line
where_single_line = false  # Where expressions have one line per clause
format_strings = true  # Break strings on multiple lines
format_macro_matchers = true  # Format macro matches
format_macro_bodies = true  # Format macro bodies
hard_tabs = false  # Use spaces instead of tabs
imports_indent = "Block"  # Use fixed indentation on import blocks
imports_layout = "HorizontalVertical"  # Go horizontal unless too long
merge_imports = true  # Merge imports into the most compact form possible
match_block_trailing_comma = true  # Put a trailing comma on match blocks
max_width = 100  # Allow code to go up to 100 characters long
merge_derives = true  # Merge all derives into one
force_multiline_blocks = true  # Force multiline closure / match to be blocks
newline_style = "Unix"  # Always use unix line endings
normalize_comments = true  # Use `//` over `/*` for comments
remove_nested_parens = true  # Remove superfluous parenthesis
reorder_imports = true  # Put imports in alphabetical order
reorder_modules = true  # Put modules in alphabetical order
space_after_colon = true  # Put spaces after typing colons
space_before_colon = false  # Do not put spaces before typing colons
struct_field_align_threshold = 0  # Do not align struct field types
spaces_around_ranges = false  # Do not put spaces around range specifiers
struct_lit_single_line = true  # Allow struct literals on a single line
tab_spaces = 4  # Four spaces per tab
trailing_comma = "Vertical"  # Put trailing commas in vertical lists
trailing_semicolon = true  # Add semicolons after control statements like return
type_punctuation_density = "Wide"  # Put spaces around type punctuation
use_field_init_shorthand = true  # Where possible, will convert to short inits
use_try_shorthand = true  # Where possible, replaces `try!` with `?`
format_doc_comments = true  # Format code in documentation comments
wrap_comments = true  # Wrap long comments onto multiple lines
match_arm_blocks = true  # Wrap line broken match arms in blocks
overflow_delimited_expr = false  # Do not allow only list objects to line break
blank_lines_upper_bound = 1  # Allow at most 1 blank line between items
blank_lines_lower_bound = 0  # Allow at a minimum 0 lines between each item
unstable_features = true  # Allow unstable features
edition = "2018"  # Format for 2018 edition of rust
normalize_doc_attributes = true  # Do not use documentation attributes
inline_attribute_width = 0  # Do not write items and attributes on the same line